### ISSUE TITLE
Heads up on using the literate-nav plugin

### ISSUE THREAD

**Issue by nikita-petko** [jmkd3v/robloxapi-wiki#6]
There is an issue with the literate-nav plugin that will cause an invalid entry on a sitemap.

As you can see here:
https://github.com/jmkd3v/robloxapi-wiki/blob/16d37da4f1476a2b2512e94b89e50644a0c5c383/sitemap.xml#L8-L12

The `loc` key is None.

This will bring up issues when trying to request crawling from Google as it cannot parse the sitemap correctly:
![image](https://user-images.githubusercontent.com/79342039/164566544-7be94689-a97e-47a0-8db4-37764a850731.png)

You can go by fixing this by either not using literate-nav plugin, making every markdown file that has a directory to it an index.md to that directory (say docs/test.md also had a child of docs/test/other.md, you would move docs/test.md to docs/test/index.md so it doesn't produce duplicate nav entries) and use the following theme features:
- [Navigation Tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs)
- [Navigation Sections](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections)
- [More...](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation)

I hope this can help address this issue if you ever come accross it in the future if you request indexing by sitemaps

**Comment by jmkd3v** [comment]
Is there an open issue with the plugin? Why is it doing this?

**Comment by nikita-petko** [comment]
There's no issue about it as far as I am sure.

But I believe the main reason it occurs is because the SUMMARY.md file is technically hidden, and maybe https://github.com/oprypin/mkdocs-literate-nav/issues/4 addresses this?

Anyway, if you analyze the sitemap, you'll see that there is no entry for /SUMMARY/index.html, despite the fact that it is a file that exists, my theory is that the None entry correlates to this.
https://staging.robloxapi.wiki/SUMMARY/index.html
https://github.com/jmkd3v/robloxapi-wiki/blob/gh-pages/SUMMARY/index.html

**Comment by jmkd3v** [comment]
It shouldn't be visible because the sitemap file is only used to construct the sidebar, so it shouldn't even be an entry at all. If it can be ignored and Google will read it anyways (which is what I understand from "sitemap can be read, but has errors") then I don't see an issue.

**Comment by nikita-petko** [comment]
You can't ignore the error though

**Comment by jmkd3v** [comment]
What does that mean? If it means that Google can't index the site, that is something we should fix - if they ignore it, then we're fine.

**Comment by nikita-petko** [comment]
I am talking about the fact that you cannot make the Google Search Console ignore the error when it's reading the sitemap.

**Comment by jmkd3v** [comment]
Does that matter? If it can still parse and show results for the site, it doesn't matter if the search console has an error.
